# name of the software
name: .NET client library for Digipost API

# url of the download button
downloadUrl: https://www.nuget.org/packages/digipost-api-client/
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

baseurl: "/digipost-api-client-dotnet"

currentCollecion: "v8"
currentVersion: "8"
versions: ["8", "7", "6.2", "6.1", "6.0"]

collections:
  v6_0:  
    output: true
    permalink: /v6.0/    
  v6_1:
    output: true
    permalink: /v6.1/
  v6_2:
    output: true
    permalink: /v6.2/
  v7:  
    output: true
    permalink: /v7/ 
  v8:  
    output: true
    permalink: /v8/    

# list of additional links on the right of the top menu
headerLinks:
  - title: Download library
    url: https://www.nuget.org/packages/digipost-api-client/
  - title: GitHub
    url: https://github.com/digipost/digipost-api-client-dotnet
  - title: Digipost
    url: https://www.digipost.no

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/digipost/digipost-api-client-dotnet
  - title: Issues
    url: https://github.com/digipost/digipost-api-client-dotnet/issues

# header
header:
  color1: "#e32d22"
  color2:
  trianglify: false

# github buttons
githubButton:
  user: digipost
  repo: digipost-api-client-dotnet

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account: digipost_no

# facebook buttons
facebook:
  enabled: false
  profileUrl:

# google analytics
analytics:
  trackingid: UA-77734017-1
  domain: auto

# DON'T MODIFY
highlight: rouge

gems:
  - jekyll-redirect-from

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']